name: firebase_performance_example
description: Demonstrates how to use the firebase_performance plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  http: ^0.12.0
  flutter:
    sdk: flutter
  firebase_performance:
    path: ../
  firebase_core: ^0.4.0

dev_dependencies:
  e2e: ^0.2.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
