name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
    path: ../
  google_sign_in: ^4.0.0
  firebase_core: ^0.4.4
  firebase_dynamic_links: ^0.3.0
  uuid: ^2.0.2

dev_dependencies:
  pedantic: ^1.8.0
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.2.1

flutter:
  uses-material-design: true
