name: cloud_functions_example
description: Demonstrates how to use the cloud_functions plugin.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_functions:
    path: ..
  firebase_core: ^0.4.4

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any


flutter:
  uses-material-design: true

